import { ChaosStreamProxyInstance } from '../types'

// In development, Vite proxy will handle /api requests
// In production, set VITE_API_URL to your backend URL
const API_BASE_URL = import.meta.env.VITE_API_URL || ''

export interface OSCInstance {
  name: string
  url?: string
  statefulmode?: boolean
}

export async function listChaosProxyInstances(): Promise<ChaosStreamProxyInstance[]> {
  try {
    const response = await fetch(`${API_BASE_URL}/api/chaos-proxy/instances`)

    if (!response.ok) {
      const error = await response.json()
      throw new Error(error.message || `HTTP error! status: ${response.status}`)
    }

    const data = await response.json()
    return data.instances
  } catch (error) {
    console.error('Failed to list instances:', error)
    throw error
  }
}

export async function createChaosProxyInstance(
  name: string,
  statefulMode: boolean
): Promise<ChaosStreamProxyInstance> {
  try {
    const response = await fetch(`${API_BASE_URL}/api/chaos-proxy/instances`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ name, statefulMode })
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(error.message || `HTTP error! status: ${response.status}`)
    }

    const data = await response.json()
    return data.instance
  } catch (error) {
    console.error('Failed to create instance:', error)
    throw error
  }
}

export async function deleteChaosProxyInstance(name: string): Promise<void> {
  try {
    const response = await fetch(`${API_BASE_URL}/api/chaos-proxy/instances/${name}`, {
      method: 'DELETE'
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(error.message || `HTTP error! status: ${response.status}`)
    }
  } catch (error) {
    console.error('Failed to delete instance:', error)
    throw error
  }
}

export async function describeChaosProxyInstance(name: string): Promise<OSCInstance | null> {
  try {
    const response = await fetch(`${API_BASE_URL}/api/chaos-proxy/instances/${name}`)

    if (!response.ok) {
      if (response.status === 404) {
        return null
      }
      throw new Error(`HTTP error! status: ${response.status}`)
    }

    const data = await response.json()
    return data.instance
  } catch (error) {
    console.error('Failed to describe instance:', error)
    throw error
  }
}

export interface ValidationResult {
  valid: boolean
  message: string
  statusCode?: number
}

export async function validateChaosProxyUrl(url: string): Promise<ValidationResult> {
  try {
    const response = await fetch(`${API_BASE_URL}/api/chaos-proxy/validate`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ url })
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(error.message || `HTTP error! status: ${response.status}`)
    }

    const data = await response.json()
    return data
  } catch (error) {
    console.error('Failed to validate proxy URL:', error)
    throw error
  }
}

export interface ProxyConfiguration {
  name: string
  instanceUrl: string
  sourceUrl: string
  protocol: 'hls' | 'dash'
  streamType?: 'live' | 'vod'
  description?: string
  delays: any[]
  statusCodes: any[]
  timeouts: any[]
  throttles: any[]
  proxyUrl?: string  // Generated by backend
  redirectUrl?: string  // Generated by backend
}

export async function saveProxyConfiguration(config: ProxyConfiguration): Promise<void> {
  try {
    const response = await fetch(`${API_BASE_URL}/api/config`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(config)
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(error.message || `HTTP error! status: ${response.status}`)
    }
  } catch (error) {
    console.error('Failed to save configuration:', error)
    throw error
  }
}

export async function listProxyConfigurations(): Promise<ProxyConfiguration[]> {
  try {
    const response = await fetch(`${API_BASE_URL}/api/config`)

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`)
    }

    const data = await response.json()
    return data.configs
  } catch (error) {
    console.error('Failed to list configurations:', error)
    throw error
  }
}

export async function getProxyConfiguration(name: string, protocol: 'hls' | 'dash'): Promise<ProxyConfiguration | null> {
  try {
    const response = await fetch(`${API_BASE_URL}/api/config/${name}/${protocol}`)

    if (!response.ok) {
      if (response.status === 404) {
        return null
      }
      throw new Error(`HTTP error! status: ${response.status}`)
    }

    const data = await response.json()
    return data.config
  } catch (error) {
    console.error('Failed to get configuration:', error)
    throw error
  }
}

export async function deleteProxyConfiguration(name: string, protocol: 'hls' | 'dash'): Promise<void> {
  try {
    const response = await fetch(`${API_BASE_URL}/api/config/${name}/${protocol}`, {
      method: 'DELETE'
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(error.message || `HTTP error! status: ${response.status}`)
    }
  } catch (error) {
    console.error('Failed to delete configuration:', error)
    throw error
  }
}
